/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Stream.app;
import static Stream.app.MessageUtils.getMessage;

import lombok.extern.slf4j.Slf4j;
import org.apache.commons.text.WordUtils;

@Slf4j
public class App {
    public static void main(String[] args) {
        log.info("Server started");
    }
}
