# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3"
services:
  server1:
    image: stream:0.22
    container_name: n0
    hostname: n0
    volumes:
      - ../../../:/opt/ratis
    ports:
      - 9864
    environment:
      - SEED_DNS=n0
      - IS_SEED='true'
    command: [ "/home/bin/server.sh", "filestore", "server",
               "--id", "n0", "--storage", "/tmp/data",
               "--peers", "n0:n0:9864",
               "--raftGroup", "shard_group_0000" ]

  server2:
    image: stream:0.22
    container_name: n2
    hostname: n2
    volumes:
      - ../../../:/opt/ratis
    ports:
      - 9865
    environment:
      - SEED_DNS=n0
    command: [ "/home/bin/server.sh", "filestore", "server",
               "--id", "n2", "--storage", "/tmp/data",
               "--peers", "n2:n2:9865",
               "--raftGroup", "shard_group_0001" ]
  server3:
    image: stream:0.22
    container_name: n3
    hostname: n3
    volumes:
      - ../../../:/opt/ratis
    ports:
      - 9865
    environment:
      - SEED_DNS=n0
    command: [ "/home/bin/server.sh", "filestore", "server",
               "--id", "n3", "--storage", "/tmp/data",
               "--peers", "n3:n3:9865",
               "--raftGroup", "shard_group_0002" ]


  client1:
    image: stream:0.22
    container_name: client1
    hostname: client1
    volumes:
      - ../../../:/opt/ratis
    ports:
      - 9869
    command: [ "sleep", "infinity" ]
